### ISSUE TITLE
Failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized

### ISSUE THREAD

**Issue by gopricy** [NVIDIA/gpu-operator#748] opened 2024-06-11 17:29 UTC
### 1. Quick Debug Information
* OS/Version: Ubuntu22.04
* Kernel Version: 5.15
* Container Runtime Type: Containerd 1.6.33
* K8s Flavor/Version: K8S
* GPU Operator Version: N/A

### 2. Issue or feature description
Helm chart repo seems down now.

### 3. Steps to reproduce the issue
Running `helm repo add --pass-credentials nvidia https://helm.ngc.nvidia.com/nvidia`
Received `Error: looks like "https://helm.ngc.nvidia.com/nvidia" is not a valid chart repository or cannot be reached: failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized`

**Comment by TornjV** [comment] 2024-06-11 17:54
+1

Blocking our pipelines for CD right now

**Comment by takirala** [comment] 2024-06-11 17:54
+1 blocking our CI/CD as well

**Comment by cwyl02** [comment] 2024-06-11 17:55
+1 this is blocking our CI/CD as well

**Comment by Parth-Sabhadiya-Imprivata** [comment] 2024-06-11 18:24
+1 this is blocking gpu upgrade for us

**Comment by gopricy** [comment] 2024-06-11 20:37
btw, is it considered a outage?
checked the status page which claimed operational, hope it can catch it
https://status.ngc.nvidia.com/

**Comment by MxNxPx** [comment] 2024-06-11 21:32
seems to be working again; but curious to know root cause.

**Comment by cdesiniotis** [comment] 2024-06-11 21:41
This issue should be resolved now. 

@gopricy I am closing this, but please re-open if you are still experiencing this issue.

**Closed by cdesiniotis** 2024-06-11 21:41 UTC

**Comment by shashiranjan84** [comment] 2024-06-14 18:42
Got this today `https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized`

**Comment by cwyl02** [comment] 2024-08-14 00:34
this is happening again

**Comment by klueska** [comment] 2024-08-14 15:33
The team is aware of it and working to fix it now.
