### ISSUE TITLE
gpu operator 1.8.1 / 470.57.02 / nvidia-driver-daemonset pod crashloop

### ISSUE THREAD

**Issue by yug0slav** [NVIDIA/gpu-operator#252] opened 2021-09-01 16:17 UTC
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [no] Are you running on an Ubuntu 18.04 node? - CentOS7.9
- [yes] Are you running Kubernetes v1.13+? - 1.21
- [containerd] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? - 1.4.8+
- [N/A] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [yes] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
- nvidia-driver-daemonset pod crashloop
```
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Proceeding with Linux kernel version 3.10.0-1160.36.2.el7.x86_64
Installing Linux kernel headers...
Installing Linux kernel module files...
Generating Linux kernel version string...
Compiling NVIDIA driver kernel modules...
In file included from /usr/src/nvidia-470.57.02/kernel/nvidia/nv-kthread-q.c:25:0:
/usr/src/nvidia-470.57.02/kernel/common/inc/nv-list-helpers.h:81:0: warning: "hlist_entry_safe" redefined [enabled by default]
 #define hlist_entry_safe(ptr, type, member) \
 ^
In file included from /usr/src/nvidia-470.57.02/kernel/common/inc/nv-kthread-q.h:28:0,
                 from /usr/src/nvidia-470.57.02/kernel/nvidia/nv-kthread-q.c:24:
include/linux/list.h:743:0: note: this is the location of the previous definition
 #define hlist_entry_safe(ptr, type, member) \
 ^
In file included from /usr/src/nvidia-470.57.02/kernel/nvidia-uvm/uvm_rb_tree.h:32:0,
                 from /usr/src/nvidia-470.57.02/kernel/nvidia-uvm/uvm_rb_tree.c:24:
/usr/src/nvidia-470.57.02/kernel/common/inc/nv-list-helpers.h:81:0: warning: "hlist_entry_safe" redefined [enabled by default]
 #define hlist_entry_safe(ptr, type, member) \
 ^
In file included from include/linux/preempt.h:11:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/rcupdate.h:38,
                 from include/linux/rbtree.h:34,
                 from /usr/src/nvidia-470.57.02/kernel/nvidia-uvm/uvm_rb_tree.h:29,
                 from /usr/src/nvidia-470.57.02/kernel/nvidia-uvm/uvm_rb_tree.c:24:
include/linux/list.h:743:0: note: this is the location of the previous definition
 #define hlist_entry_safe(ptr, type, member) \
 ^
...

Building NVIDIA driver package nvidia-modules-3.10.0...
Cleaning up the package cache...
Installing NVIDIA driver kernel modules...

WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.


ERROR: Unable to open 'kernel/dkms.conf' for copying (No such file or directory)


Welcome to the NVIDIA Software Installer for Unix/Linux


ERROR: Unable to find the development tool `cc` in your path; please make sure that you have the package 'gcc' installed.  If gcc is installed on your system, then please check that `cc` is in your PATH.


ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

Detected 72 CPUs online; setting concurrency level to 32.
Installing NVIDIA driver version 470.57.02.
A precompiled kernel interface for kernel '3.10.0-1160.36.2.el7.x86_64' has been found here: ./kernel/precompiled/nvidia-modules-3.10.0.
Required file 'nv-peermem-linux.o' not found in package './kernel/precompiled/nvidia-modules-3.10.0'
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs... 
```

### 2. Steps to reproduce the issue
- deploy nvidia operator helm chart with minor value.yaml changes   
   - psp.enabled=true
   - defaultRuntime: container
   - toolkit.version: devel-centos7
   
- FYI: works if I change version to 460.73.01

**Comment by cdesiniotis** [comment] 2021-09-01 16:21
Yes we have been made aware our 470.57.02 image for centos is failing. Please use the 460 driver until this is resolved.

**Comment by cdesiniotis** [comment] 2021-09-02 22:15
@yug0slav we just pushed new images for 470.57.02. Could you give the new image a try? `nvcr.io/nvidia/driver:470.57.02-centos7`

**Comment by shivamerla** [comment] 2021-09-07 20:06
Closing this as the issue is fixed with updated driver image. Please re-open if its still failing.

**Closed by shivamerla** 2021-09-07 20:06 UTC
