### ISSUE TITLE
nvidia-driver DaemonSet Pods are crashing in OCP 4.7.21

### ISSUE THREAD

**Issue by koflerm** [NVIDIA/gpu-operator#234] opened 2021-08-03 15:44 UTC
We are currently using the GPU operator version 1.7.1 in our OpenShift clusters.

Unfortunately, after updating to OpenShift 4.7.21 the nvidia-driver DaemonSet pods crash with the following error:

```
Installing Linux kernel headers...
+ echo 'Installing Linux kernel headers...'
+ dnf -q -y --releasever=8.3 install kernel-headers-4.18.0-240.23.2.el8_3.x86_64 kernel-devel-4.18.0-240.23.2.el8_3.x86_64
Error: Unable to find a match: kernel-headers-4.18.0-240.23.2.el8_3.x86_64 kernel-devel-4.18.0-240.23.2.el8_3.x86_64
```

Do you know what the problem could be here? Is maybe the correct kernel headers package missing for OpenShift 4.7.21?

**Comment by shivamerla** [comment] 2021-08-03 16:22
@kpouget @omertuc Can you please help checking if it's due to missing kernel headers for this version or entitlement issue?

@koflerm can you verify if entitlement keys are valid by running this test pod mentioned here: https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-install-gpu-operator-via-helmv3

**Comment by kpouget** [comment] 2021-08-03 17:00
Hello @koflerm, 

we also saw this problem, it is caused by an entitlement file too old (still valid, but not giving access to `rhocp-4.7` repositories).
Could you try regenerating the entitlement file and try again?

```
+ dnf list kernel-core --showduplicates
...
kernel-core.x86_64    4.18.0-240.23.2.el8_3     rhocp-4.7-for-rhel-8-x86_64-rpms
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-gpu-operator-e2e-170/1422331589974560768/artifacts/gpu-operator-e2e-170/nightly/artifacts/003__entitlement__wait/entitlement-test.pod.log

**Comment by koflerm** [comment] 2021-08-04 07:20
Hello @kpouget,

Just regenerated the entitlement certificate but I am still not able to retrieve the package. Maybe one hint I am using a RHEL 8 Premium Subscription entitlement so before the kernel-headers package was available in rhel-8-for-x86_64-baseos-eus-rpms. Now, it is available (as you mentioned) in rhocp-4.7-for-rhel-8-x86_64-rpms so do you need a different subscription for that?

**Comment by kpouget** [comment] 2021-08-04 11:05
@koflerm could you attach the logs of the driver container, just to confirm that it's failing to enable `rhocp-4.7-for-rhel-8-x86_64-rpms` repo?

**Comment by shivamerla** [comment] 2021-08-27 23:01
@koflerm are you still hitting this issue. Closing this as its been an while, please re-open if the issue is still not resolved with entitlements.

**Closed by shivamerla** 2021-08-27 23:01 UTC

**Comment by koflerm** [comment] 2021-08-28 06:47
@shivamerla sorry for not answering we fixed this problem by just using the entitlement of one of our OpenShift subscriptions instead of the entitlement of a premium RHEL subscription. We can keep this issue closed.
