### ISSUE TITLE
Deploy GPU Operators in a disconnected or airgapped environment v22.9.0

### ISSUE THREAD

**Issue by chenxj1997** [NVIDIA/gpu-operator#436] opened 2022-11-08 12:43 UTC
An error occurred ，when I'm installing gpu-operator-v22.9.0 as follows
Error:INATLLATION FAILED:unable to build kubernetes objects from release mainfest: error validating:" " :error validating data :[ValidationError(ClusterOolicy.spec.dcgmExporter):unknown field "enable" in com.nvidia.v1.ClusterPlicy.spec.dcgmExporter,ValidationError(ClusterOolicy.spec.dcgmExporter):unknown field "serviceMonitor" in com.nvidia.v1.ClusterPlicy.spec.dcgmExporter,ValidationError(ClusterOolicy.spec.devicePlugin):unknown field "enable" in com.nvidia.v1.ClusterPlicy.spec.devicePlugin,ValidationError(ClusterOolicy.spec.driver):unknown field "rollingUpdate" in com.nvidia.v1.ClusterPlicy.spec.driver,ValidationError(ClusterOolicy.spec.gfd):unknown field "enable" in com.nvidia.v1.ClusterPlicy.spec.gfd,ValidationError(ClusterOolicy.spec.toolkit):unknown field "installDir" in com.nvidia.v1.ClusterPlicy.spec.toolkit]
What should I do?

**Comment by shivamerla** [comment] 2022-11-09 16:14
Closing this as duplicate of #435

**Closed by shivamerla** 2022-11-09 16:14 UTC
